---
title: "BoletinTema1RUBENPENYA"
author: "Ruben Peña Sanchez"
date: "2023-02-15"
output: html_document
---

Ejercicio 1 

A

```{r}
??MASS
??Animals2
```
B
```{r}
dim(MASS::Animals)
head(MASS::Animals)
tail(MASS::Animals)
str(MASS::Animals)
dim(robustbase::Animals2)
head (robustbase::Animals2)
tail(robustbase::Animals2)
str(robustbase::Animals2)
```
C

```{r}
rownames(MASS::Animals)
colnames(MASS::Animals)
rownames(robustbase::Animals2)
colnames(robustbase::Animals2)
```
D
```{r}
commonAnimals<- dplyr::intersect(rownames(MASS::Animals),rownames(robustbase::Animals2))
commonAnimals
```

E

Son 37, son animales menos comunes que los que si coinciden en ambos conjuntos.

```{r}
setdiff(rownames(robustbase::Animals2),rownames(MASS::Animals))
```

F

Son animales menos comunes

Ejercicio 2

```{r}
install.packages("qqPlot")
```
El qqPlot no me funciona

Ejercicio 3
```{r}
library()
libReturn<-71
head(library)
```

Ejercicio 4 A
```{r}
??MASS::cabbages
dim(MASS::cabbages)
head(MASS::cabbages)
tail(MASS::cabbages)
str(MASS::cabbages)
```

B
```{r}
is.na(MASS::cabbages)
```
C
```{r}
??carData::CHile
dim(carData::Chile)
head(carData::Chile)
tail(carData::Chile)
str (carData::Chile)
is.na(carData::Chile)
```
D
```{r}
summary(MASS::cabbages)
summary(carData::Chile)
```
Ejercicio 6

Se pueden apreciar cambios en la vitanima 
```{r}
massca<-data.frame(MASS::cabbages)
histo<-split(massca,massca$Cult)
hist(histo$c39$VitC)
hist(histo$c52$VitC)

```
Ejercicio 7

```{r}
#Diagrama de dispersión global.
plot(MASS::whiteside$Temp, MASS::whiteside$Gas)
#Diagrama de dispersión etiquetando según un factor.
plot(MASS::whiteside$Temp, MASS::whiteside$Gas, pch=c(6,16)[MASS::whiteside$Insul])
legend(x="topright",legend=c("Insul = Before","Insul = After"), pch=c(6,16))
# Planteamos 2 modelos lineales, uno para los datos de cada factor
Model1 <- lm(Gas ~ Temp, data = MASS::whiteside, subset = which(Insul == "Before"))
Model2 <- lm(Gas ~ Temp, data = MASS::whiteside, subset = which(Insul == "After"))
# Representamos las rectas correspondientes a cada modelo lineal
abline(Model1, lty=2)
abline(Model2)

```
```{r}
#Diagrama de dispersión global.
plot(MASS::cabbages$VitC, MASS::cabbages$HeadWt)
#Diagrama de dispersión etiquetando según un factor.
plot(MASS::cabbages$VitC, MASS::cabbages$HeadWt, pch=c(6,16))
legend(x="topright", pch=c(6,16))
# Planteamos 2 modelos lineales, uno para los datos de cada factor
Model2 <- lm(VitC ~ HeadWt, data = MASS::cabbages)
# Representamos las rectas correspondientes a cada modelo lineal
abline(Model2)
```
Ejercicio 7 C

```{r}
summary(Model2)
```

